# Generated by Django 4.2 on 2023-04-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_person_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='phone_no',
            new_name='phoneno',
        ),
    ]
