# Generated by Django 4.2 on 2023-04-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='state',
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
